# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test branch

on:
  push:
    branches: [ '**', '!master' ] # all branches except master
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest # gets the data from strategy.matrix.o
    strategy:
      matrix:
        node-version: [ 10.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    # Checkout actions
    - uses: actions/checkout@v2
    - name: Checkout and use Node ${{ matrix.node-version }}
      # Setup node action
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test
