# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish packages at NPM

on:
  push:
    branches: [ 'master' ] # push on master?
  pull_request:
    branches: [ master ] # merge on master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn test
  
  publish-at-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      #- run: yarn global add lerna
      - run: sh node_modules/.bin/lerna publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
