# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish packages at NPM

on:
  push:
    branches: [ 'master' ] # push on master?
  pull_request:
    branches: [ master ] # merge on master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: yarn install
      - run: yarn test
  
  version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/jhderojasUVa/github-monorepo-actions
      - name: Versioning
        run: npmx lerna version --yes

  publish-at-npm:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # pulls all commits (needed for lerna / semantic release to correctly version)
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GIT_TOKEN}@github.com/jhderojasUVa/github-monorepo-actions
      #- run: yarn global add lerna # No need for this
      #- run: yarn install # No need for this
      # pulls all tags (needed for lerna / semantic release to correctly version)
      #- run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: npx lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
